### ISSUE TITLE
var L = require('leaflet') is not defined

### ISSUE THREAD

**Issue by soli004** [timwis/leaflet-choropleth#27]
Trying to use the leaflet plugin but I get errors at" choropleth.js:1" Uncaught ReferenceError: require choropleth.js:1 is not defined. Error shows up here "var L = require('leaflet')".

I have no clue why.
I am using chrome with the developer tools
![printscreen 2018-01-01 kl 22 01 08](https://user-images.githubusercontent.com/5410735/34471081-5c21f2a4-ef3f-11e7-977f-fe4455f703fd.jpg)

Thanks

**Comment by timwis** [comment]
Are you using browserify/webpack or just a `<script>` tag? If the latter, make sure you're pointing to the version inside `dist/` not `src/`.

**Comment by soli004** [comment]
Yes from a <script> tag. I enter this line and I get the error in chrome developer tool. I have not called the script yet

2 jan. 2018 kl. 02:21 skrev Tim Wisniewski <notifications@github.com<mailto:notifications@github.com>>:


Are you using browserify/webpack or just a <script> tag?

**Comment by timwis** [comment]
Did you try changing it to point to the `dist/` file instead of the `src/` file like I suggested?

**Comment by soli004** [comment]
I did copy the dist to the basic folder the error is gone but a new one turned up...
Is there a way to get around this problem? It seems to be a browser problem, I use a local server MAMP and Chrome. Thanks
![printscreen 2018-01-03 kl 17 28 41](https://user-images.githubusercontent.com/5410735/34529370-f4ab43dc-f0ab-11e7-9d75-26618f471a9f.jpg)

**Comment by soli004** [comment]
OK, I was able to deactivate Cross-Origin under developer tool in Safari, I see what I can do in Chrome...

**Comment by timwis** [comment]
It looks like you're trying to load your webpage as a file rather than via a local web server. The problem you're experiencing would happen with any module, and is not specific to leaflet-choropleth. I recommend you run a local web server on your computer for your development. The [three.js docs](https://threejs.org/docs/index.html#manual/introduction/How-to-run-thing-locally) have a good write-up about how to run things locally. Three.js has nothing to do with leaflet, but the problem you're describing is one faced by every web developer when they're getting started, so they cover it in their docs too. Hope that helps.

**Comment by soli004** [comment]
Tim, I solved the issue by using Safari instead of Chrome as it had a way to deactivate "Cross-origin" and I am using a local web. Thanks,
i'ts now working

Tim Wisniewski<mailto:notifications@github.com>
4 januari 2018 03:21

It looks like you're trying to load your webpage as a file rather than via a local web server. The problem you're experiencing would happen with any module, and is not specific to leaflet-choropleth. I recommend you run a local web server on your computer for your development. The three.js docs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fthreejs.org%2Fdocs%2Findex.html%23manual%2Fintroduction%2FHow-to-run-thing-locally&data=02%7C01%7C%7C8e9dfc9a70db4ea206d708d55319ee38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636506293187355103&sdata=dYn4OiJtUTS7GU8NV3C9xNOo9bUfUxVl2mJki4rxnrw%3D&reserved=0> have a good write-up about how to run things locally. Three.js has nothing to do with leaflet, but the problem you're describing is one faced by every web developer when they're getting started, so they cover it in their docs too. Hope that helps.
