### ISSUE TITLE
Demo: File not found

### ISSUE THREAD

**Issue by alexandre-mbm** [timwis/leaflet-choropleth#4]
http://timwis.com/leaflet-choropleth/demo

_Update: fixed with http://timwis.com/leaflet-choropleth/examples/basic_

**Comment by timwis** [comment]
Thanks @alexandre-mbm - did you get that URL from npmjs.org ? I believe I fixed it elsewhere, but I'll fix it there too (just seems silly that I have to increment the version to refresh the readme there)

**Comment by alexandre-mbm** [comment]
I got the URL from GitHub's header. It still do not work.

**Comment by timwis** [comment]
oh my goodness I'm blind @alexandre-mbm. URL fixed! thanks :P

**Comment by alexandre-mbm** [comment]
OK. Thanks. Congratulations by tool! I was seeking something like it time ago.

**Comment by timwis** [comment]
Thanks! I'm glad you found it useful

**Comment by alexandre-mbm** [comment]
To be better for **non programmers** users, just someone to create builders from your demos, that receives GeoJSON data and makes possible choose a color palette like happens at [colorbrewer2.org](http://colorbrewer2.org).

But, yes, I understand that your project is targeted to programmers.

**Comment by timwis** [comment]
@alexandre-mbm I don't quite understand - are you suggesting a feature or suggesting we integrate with colorbrewer2.org?

**Comment by timwis** [comment]
by the way @alexandre-mbm, cartodb.com has a _super_ easy way to make a choropleth map for non programmers if you haven't seen it

**Comment by alexandre-mbm** [comment]
A brother small project of this. No, I still will see the [cartodb.com](https://cartodb.com/). Thanks!
